package pojos;
// Generated 01-mar-2024 15:20:17 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Asignatura generated by hbm2java
 */
public class Asignatura  implements java.io.Serializable {


     private Integer codAsignatura;
     private String nombreAsignatura;
     private Integer creditos;
     private Set notases = new HashSet(0);

    public Asignatura() {
    }

    public Asignatura(String nombreAsignatura, Integer creditos, Set notases) {
       this.nombreAsignatura = nombreAsignatura;
       this.creditos = creditos;
       this.notases = notases;
    }
   
    public Integer getCodAsignatura() {
        return this.codAsignatura;
    }
    
    public void setCodAsignatura(Integer codAsignatura) {
        this.codAsignatura = codAsignatura;
    }
    public String getNombreAsignatura() {
        return this.nombreAsignatura;
    }
    
    public void setNombreAsignatura(String nombreAsignatura) {
        this.nombreAsignatura = nombreAsignatura;
    }
    public Integer getCreditos() {
        return this.creditos;
    }
    
    public void setCreditos(Integer creditos) {
        this.creditos = creditos;
    }
    public Set getNotases() {
        return this.notases;
    }
    
    public void setNotases(Set notases) {
        this.notases = notases;
    }




}


