package pojos;
// Generated 01-mar-2024 12:26:04 by Hibernate Tools 4.3.1



/**
 * NotasId generated by hbm2java
 */
public class NotasId  implements java.io.Serializable {


     private int codAlu;
     private int codAsignatura;

    public NotasId() {
    }

    public NotasId(int codAlu, int codAsignatura) {
       this.codAlu = codAlu;
       this.codAsignatura = codAsignatura;
    }
   
    public int getCodAlu() {
        return this.codAlu;
    }
    
    public void setCodAlu(int codAlu) {
        this.codAlu = codAlu;
    }
    public int getCodAsignatura() {
        return this.codAsignatura;
    }
    
    public void setCodAsignatura(int codAsignatura) {
        this.codAsignatura = codAsignatura;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof NotasId) ) return false;
		 NotasId castOther = ( NotasId ) other; 
         
		 return (this.getCodAlu()==castOther.getCodAlu())
 && (this.getCodAsignatura()==castOther.getCodAsignatura());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCodAlu();
         result = 37 * result + this.getCodAsignatura();
         return result;
   }   


}


