package pojos;
// Generated 01-mar-2024 15:20:17 by Hibernate Tools 4.3.1



/**
 * Telefonos generated by hbm2java
 */
public class Telefonos  implements java.io.Serializable {


     private TelefonosId id;
     private Alumno alumno;

    public Telefonos() {
    }

    public Telefonos(TelefonosId id, Alumno alumno) {
       this.id = id;
       this.alumno = alumno;
    }
   
    public TelefonosId getId() {
        return this.id;
    }
    
    public void setId(TelefonosId id) {
        this.id = id;
    }
    public Alumno getAlumno() {
        return this.alumno;
    }
    
    public void setAlumno(Alumno alumno) {
        this.alumno = alumno;
    }




}


